services:
  shop_postgres:
    container_name: shop_postgres
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  shop_redis:
    container_name: shop_redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data: