services:
  shop_postgres:
    container_name: shop_postgres
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  shop_redis:
    container_name: shop_redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

  shop_minio:
    container_name: shop_minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address :9001 /data

volumes:
  postgres-data:
  minio: